### ISSUE TITLE
Write PDB/CIF output

### ISSUE THREAD

**Issue by danny305** [freesasa/freesasa-python#18]
Yo Simon. I am reading through your cython code and don't see anywhere how to output the freesasa structure back into a file format. 

I am trying to remove build dependencies for an undergraduate project I am creating for a CS class here at UT. They are going to demo some of our data engineering software (which freesasa is a dependency of). 

I  do not want to ask undergrads  to `./configure` and `make` dependencies and would much rather have them `pip install freesasa`. 

However, I need it to generate a freesasa pdb (which I currently turn into a cif myself) or have it generate a cif file (which we are currently working on). 

Did I happen to miss this feature in your cython code? 

If not what would it take to wrap the write_pdb functionality with cython?

**Comment by danny305** [comment]
I was going through whl installed by `pip install freesasa`. How do you feel about also installing the freesasa binary along with the shared library? Then we can just add the path to the binary to `$PATH`? I don't see a configure file do it currently but there is a makefile.am. 

Im just spit balling here looking for a quick and dirty solution. I am sure you have a much better way to go about this.

**Comment by mittinatten** [comment]
Hi,
The Python interface is a bit behind on features unfortunately, the idea was that if you're using the Python package you're more interested in getting an array of results than a file, but ideally all the CLI features should be available at some point.

Adding write pdb functionality shouldn't be too complicated, as you can see in result.pyx, we have the result-tree which can be passed to `freesasa_tree_export()`. So you would have to add that to `cfreesasa.pxd` and add a method to the Result class, that glues it together.

If we can automate it somehow, adding the freesasa CLI to the package is not a bad idea. Everything is built using the C compiler that each Python version prefers on the respective platforms. At the moment I build and publish packages for Python versions 3.6-3.8 for Windows, Linux and Mac OS X (only source for Linux) using Travis (Mac and Linux), and Appveyor (Windows). However, I doubt we can build the CLI for Windows easily, since getopt is a GNU extension to the C standard library. So if we bundle the CLI we probably need to make an exception for the Windows builds.

I don't have much experience with Python outside this package, so for me at least it is not a quick fix unfortunately, and I don't know much about distributing binaries in general, with regards to library version compatibility, etc. As you've noticed I don't use autotools here, but let the Python setup script handle everything instead (the C part of the build is a lot simpler here, it excludes libxml and json-c, doesn't handle docs and tests, etc).

I looked into making the CLI and C API a deb-package at some point, to allow easier installs in Debian, Ubuntu, etc, but it seems like it's quite a lot of work (I might be wrong). I only ever got around to creating the man pages.

**Comment by danny305** [comment]
I'll probably play with your cython code and create bindings for the tree export function.

Thanks for the feedback!

**Comment by mittinatten** [comment]
Great! Feel free to send a PR in case it works out.

**Comment by danny305** [comment]
If I get you a PR with a  working version, would you be down to create a beta version publicly available on PyPi by April 1st? 

I would like to have my undergrads `pip install freesasa==<beta_version>` that has the implemented feature. 

Let me know! If not I can just create a .whl file of my branch with the added functionality and just send it around in an email.

**Comment by mittinatten** [comment]
Yes, we can try that. I will be on vacation from the 29th or 30th probably, so if you have something by say friday or saturday it should be possible.

**Comment by danny305** [comment]
So I just got it working with the `freesasa.calc(structure, params)`.

However, it fails with `result, sasa_classes = freesasa.calcBioPDB(structure)`.

I am not sure why. Its failing on the C side of things. When I go look at your calcBioPDB I can see that you have comments talking about hacking it together and it not being thoroughly tested.

I think this is a good enough? It is working with pdb files obtained from rcsb, pdb-redo, and pdb2pqr.

Here is my testing script. I can update the docs with this example if you would like?

Ill make a PR later today.  

<img width="539" alt="image" src="https://user-images.githubusercontent.com/31376682/112209583-9fd25500-8be7-11eb-8bbe-4f3c0041c83e.png">

**Comment by mittinatten** [comment]
So here it is (the linux and mac builds are still pending). https://pypi.org/project/freesasa/2.2.0a1/

There is often some problem when I do this, so fingers crossed that it works on the first try this time 🤞

**Comment by mittinatten** [comment]
Seems something went wrong with the deployment script for OS X. Will look into it tomorrow. Should work in Windows and Linux for now (and maybe as a source package for OS X as well).

**Comment by mittinatten** [comment]
Ok, for some reason they are dropping in now. Guess there were two jobs triggered.
