### ISSUE TITLE
python bindings for cif functionality (read/write)

### ISSUE THREAD

**Issue by danny305** [freesasa/freesasa-python#23]
Yo Simon. I need python bindings for the work we did a few months back. Im going to see the best way to get it done and submit a PR. 

The problem I am running into is that the cif functionality is in C++ but the freesasa library is in C. 

I am not sure how you deal with this in your configure file. When I was writing the cif functionality I was compiling everything with cmake which makes it straight forward.

I am going to see how to maybe replicate this in the setup.py. 

Like always, your input/guidance is much appreciated.

**Comment by jamesmloy** [comment]
Hey @mittinatten-

I'm working with Danny on some of the protein engineering research he's doing at University.  Him and I talked and, if it's alright with you, I'm going to take a stab at implementing this.

I just have one question. You've pinned the freesasa submodule to commit 53eb6f4a, which is from 2018.  Given that Danny's changes were added way after that, we're going to have to bump that commit to something later. Do you foresee any issues with that?

Thanks!

**Comment by mittinatten** [comment]
Hey!
I am on vacation, and won’t be at a computer until August. But I’ll be
happy to review a PR when I’m back. I think it makes total sense now to
include the new features in the Python bindings, but haven’t done it myself
because I was unsure how much work it would be to wrap a mixed C/C++
library (maybe it’s trivial?). So I am happy you’re willing to do it. My
knowledge of Python is at a hobby level, so if anything looks strange or
outdated in the setup script, there might not be a good reason 😊, feel
free to come with suggestions.

The submodule is pinned to 2018 only because that’s the last time I needed
something new from the main library. There shouldn’t be any breaking
changes since then, so updating it should be ok.

Regarding the difference in API (root node vs structure node): Luckily
we’re still in beta in the main library, so we are allowed to tweak this
part without making a new release. The majority of the CIF code is only a
part of the CLI for now, so if necessary we can probably also modify it
without breaking the published interface (since the CLI should be
unaffected). But it might also be possible to rewire the Python wrapper.
Not sure what’s best without looking at the code. If you need to have minor
changes to the main library merged, I can probably review and merge them
from my phone. I have used a dev branch for PRs until now, and only merged
finished releases to master, earlier. I think I want to have PRs directly
to the master branch instead from now on.

Simon

tors 1 juli 2021 kl. 05:03 skrev James Loy ***@***.***>:

**Comment by mittinatten** [comment]
Hi, any updates here?

**Comment by mittinatten** [comment]
Closed due to inactivity.
