### ISSUE TITLE
load structure with ~ symbol?

### ISSUE THREAD

**Issue by ghost** [freesasa/freesasa-python#26]
Currently, provide a path with ~ will fail

```python
structure = freesasa.Structure("~/Desktop/1u2q.pdb")
```

We can have one-liner to support this functionality with `os.path.expanduser(fileName)`.
Not sure whether this is necessary though.

**Comment by mittinatten** [comment]
Hi! From the docs `os.path.expanduser` looks like the right solution. Since it does nothing to paths that don't have a `~` it should be fairly safe. On the other hand I'm not sure if it should be the library's responsibility to handle this or the calling code's.

As far as I can remember these two lines: https://github.com/freesasa/freesasa-python/blob/4a9bbca7db5005f3fcc7c389830a0c0a01bd8670/src/structure.pyx#L102 and https://github.com/freesasa/freesasa-python/blob/44227cfed3aae2093f86e430fb9e1e9454ac284d/src/classifier.pyx#L48, are the only two calls to `fopen()`.

So, as you say, it would be a simple change to add it, but then again, not sure it should be "fixed".  Do you know of any convention here? Is the current behavior surprising?

**Comment by ghost** [comment]
It seems like even the native `open` function does not support ~ symbol. Maybe the users need to take care of that instead.
