### ISSUE TITLE
SASA for each (isolated) chain in a model

### ISSUE THREAD

**Issue by leonchas17** [freesasa/freesasa-python#7]
In the command line interface for freeSASA, there exists the option '--separate-chains' to obtain SASA calculations for each isolated chain in a model, without previous knowledge of how many said chains there are or how they are named. I haven't been able to find a similar feature on the python module. Is it there? If not, can I request it?
For the moment, my own workaround to get the python module to get calculations for each isolated chain has been along the lines in the following example: 

import freesasa
import os
import glob
from Bio.PDB import *
parser = PDBParser()
BIOstructure = parser.get_structure('4BXZ', '4bxz.pdb')
for chain in BIOstructure.get_chains():
    BioPDBstructure = freesasa.structureFromBioPDB(chain)
    result = freesasa.calc(BioPDBstructure)
    print("total : %3f Square Angstroms" % result.totalArea())

total : 69032.241739 Square Angstroms
total : 50785.518675 Square Angstroms
total : 16180.401630 Square Angstroms
total : 11782.082594 Square Angstroms
total : 12403.649369 Square Angstroms
total : 5631.029871 Square Angstroms
total : 9890.572498 Square Angstroms
total : 8368.064074 Square Angstroms
total : 9053.277564 Square Angstroms
total : 5030.820968 Square Angstroms
total : 8643.077000 Square Angstroms
total : 4407.599070 Square Angstroms
total : 7123.638034 Square Angstroms

Any feedback on the correctness of this hack will be appreciated. 
By the way, I was only able to get this to work with version 1.71 of BioPython because get_chains() is located elsewhere in newer versions.
Also, I realize it looks like I'm trying to solve the same problem as the one mentioned on issue #6, but I'm not sure it's _exactly_ the same problem, hence my opening of this issue and my proposed workaround.

**Comment by leonchas17** [comment]
By the way, the last three lines of my code snippet should of course be indented 1 level, but I'm a GitHub newbie and didn't know how to do that :(

**Comment by leonchas17** [comment]
By the way, the last three lines of my code snippet should of course be indented 1 level, but I'm a GitHub newbie and didn't know how to do that :(

**Comment by mittinatten** [comment]
The Python API does not have all the features of the CLI, so your solution is not a bad idea. The reason I haven't bothered including all features in the Python API is exactly because it isn't that hard to do what you did. You could also have used FreeSASAs Structure class to separate the chains by looping over the atoms and adding them to separate new structures based on what chain they belong to, but that would require more code than in your example.

The difference between what you are doing and calculating SASA for the whole complex and then selecting chains, as in #6, is that in your case you ignore the presence of other chains in each calculation, whereas in the latter case the SASA will be smaller because some atoms are buried in chain-chain interfaces. This means that the difference between the two calculations will be a measure of the buried area in the complex for each chain.

To include formatted code in Github comments you can use the insert code button `<>`, or start and end a paragraph with three backticks and a specifier for the language used at the beginning: ` ```python `. You can use the preview function to verify that you got it right. (Here's the manual https://guides.github.com/features/mastering-markdown/).

**Comment by leonchas17** [comment]
Cool!

For the sake of completeness I'm posting a more polished version of my code snippet, in case anyone finds it useful:
```python
import freesasa
from Bio.PDB import *
parser = PDBParser()
BIOstructure = parser.get_structure('4BXZ', '4bxz.pdb')
for chain in BIOstructure.get_chains():
    BioPDBstructure = freesasa.structureFromBioPDB(chain)
    result = freesasa.calc(BioPDBstructure)
    print(BIOstructure.id,'_',chain.id, "total : %0.3f Square Angstroms" % result.totalArea())
```

which outputs: 
    4BXZ _ A total : 69032.241 Square Angstroms
    4BXZ _ B total : 50785.518 Square Angstroms
    4BXZ _ C total : 16180.401 Square Angstroms
    4BXZ _ D total : 11782.082 Square Angstroms
    4BXZ _ E total : 12403.649 Square Angstroms
    4BXZ _ F total : 5631.029 Square Angstroms
    4BXZ _ G total : 9890.572 Square Angstroms
    4BXZ _ H total : 8368.064 Square Angstroms
    4BXZ _ I total : 9053.277 Square Angstroms
    4BXZ _ J total : 5030.820 Square Angstroms
    4BXZ _ K total : 8643.077 Square Angstroms
    4BXZ _ L total : 4407.599 Square Angstroms
    4BXZ _ X total : 7123.638 Square Angstroms

Unfortunately, Bio.PDB aborts when it encounters coordinate numbers higher than 1000 (due to the old fortran fixed-sized columns, I guess). I do have a few PDBs with coordinate numbers higher than 1000, so I'm afraid I'll have to use FreeSASA.Structure() instead of freesasa.structureFromBioPDB()

**Comment by mittinatten** [comment]
Great! I'll close the issue for now, feel free to reopen or add more comments if you have further questions.
